<a href="https://colab.research.google.com/github/drshahizan/HPDP/blob/main/lab/submission/3H/3H_Lab1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1b - Understanding Your Data

## Step 1. Import the necessary libraries

In [2]:
import pandas as pd

## Step 2. Import the dataset from Occupation.

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user', sep = '|')
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

## Step 3. Assign it to a variable called users and use the 'user_id' as index

In [4]:
users = pd.DataFrame(df)
users.set_index('user_id', inplace=True)

## Step 4. See the first 25 entries

In [5]:
df.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

## Step 5. See the last 10 entries

In [6]:
df.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

## Step 6. What is the number of observations in the dataset?

In [7]:
len(df)

943

## Step 7. What is the number of columns in the dataset?

In [9]:
df.shape[1]

5

## Step 8. Print the name of all the columns.

In [12]:
df.columns.tolist()

['user_id', 'age', 'gender', 'occupation', 'zip_code']

## Step 9. How is the dataset indexed?

In [24]:
df.index

RangeIndex(start=0, stop=943, step=1)

## Step 10. What is the data type of each column?

In [13]:
df.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

## Step 11. Print only the occupation column

In [14]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

## Step 12. How many different occupations are in this dataset?

In [15]:
df['occupation'].nunique()

21

## Step 13. What is the most frequent occupation?

In [16]:
occupation_counts = df['occupation'].value_counts()
most_frequent_occupation = occupation_counts.idxmax()
most_frequent_occupation

'student'

## Step 14. Summarize the DataFrame.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

## Step 15. Summarize all the columns

In [18]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

## Step 16. Summarize only the occupation column

In [19]:
df['occupation'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 943 entries, 0 to 942
Series name: occupation
Non-Null Count  Dtype
--------------  -----
943 non-null    object
dtypes: object(1)
memory usage: 7.5+ KB

## Step 17. What is the mean age of users?

In [20]:
df['age'].mean()

34.05196182396607

## Step 18. What is the age with least occurrence?

In [22]:
age_counts = df['age'].value_counts()
age_with_least_occurrence = age_counts.idxmin()
age_with_least_occurrence

7