# Lab 1a - Understanding Your Data

Please use the [**Chipotle Sales dataset**](https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/chipotle.tsv) for this exercise.



### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [ ]:
path = "https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/chipotle.tsv"

chipo = pd.read_csv(path, delimiter='\t')

chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. See the first 10 entries

In [ ]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [ ]:
num_observations = chipo.shape[0]
print("Number of observations:", num_observations)

Number of observations: 4622

In [ ]:
num_observations = len(chipo)
print("Number of observations:", num_observations)

Number of observations: 4622

### Step 6. What is the number of columns in the dataset?

In [ ]:
num_columns = chipo.shape[1]
print("Number of columns:", num_columns)

Number of columns: 5

### Step 7. Print the name of all the columns.

In [ ]:
column_names = chipo.columns
print("Column names:")
for column in column_names:
    print(column)

Column names:
order_id
quantity
item_name
choice_description
item_price

### Step 8. How is the dataset indexed?

In [27]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [ ]:
most_ordered_item = chipo.groupby("item_name")["quantity"].sum().idxmax()
print("The most-ordered item is:", most_ordered_item)

The most-ordered item is: Chicken Bowl

### Step 10. For the most-ordered item, how many items were ordered?

In [ ]:
most_ordered_quantity = chipo.groupby("item_name")["quantity"].sum().max()
print(f"The quantity ordered for the Chicken Bowl is: {most_ordered_quantity}")

The quantity ordered for the Chicken Bowl is: 761

### Step 11. What was the most ordered item in the choice_description column?

In [ ]:
most_ordered_choice = chipo.groupby("choice_description")["quantity"].sum().idxmax()
most_ordered_choice_quantity = chipo.groupby("choice_description")["quantity"].sum().max()

print("The most-ordered choice description is:", most_ordered_choice)
print("The quantity ordered for the most-ordered choice description is:", most_ordered_choice_quantity)

The most-ordered choice description is: [Diet Coke]
The quantity ordered for the most-ordered choice description is: 159

### Step 12. How many items were orderd in total?

In [ ]:
total_items_ordered = chipo["quantity"].sum()
print("Total number of items ordered:", total_items_ordered)

Total number of items ordered: 4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [ ]:
chipo.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [ ]:
# Define a lambda function to convert values to float
convert_to_float = lambda x: float(x.replace('$', ''))

# Apply the lambda function to the 'item_price' column
chipo['item_price'] = chipo['item_price'].apply(convert_to_float)

# Check the data type of the 'item_price' column
item_price_type = chipo['item_price'].dtype

print("Data type of 'item_price':", item_price_type)

Data type of 'item_price': float64

#### Step 13.c. Check the item price type

In [ ]:
item_price_type = chipo['item_price'].dtype

print("Data type of 'item_price':", item_price_type)

Data type of 'item_price': float64

### Step 14. How much was the revenue for the period in the dataset?

In [ ]:
chipo['revenue'] = chipo['quantity'] * chipo['item_price']
total_revenue = chipo['revenue'].sum()
print("Total revenue for the period:$", total_revenue)

Total revenue for the period:$ 39237.02

### Step 15. How many orders were made in the period?

In [ ]:
# Count the number of unique order IDs
num_orders = chipo['order_id'].nunique()

print("Number of orders made in the period:", num_orders)

Number of orders made in the period: 1834

### Step 16. What is the average revenue amount per order?

In [ ]:
total_revenue = chipo['revenue'].sum()

num_orders = chipo['order_id'].nunique()

average_revenue_per_order = total_revenue / num_orders

print("Average revenue amount per order:", average_revenue_per_order)

Average revenue amount per order: 21.39423118865867

In [ ]:
average_revenue_per_order = chipo.groupby("order_id")["revenue"].sum().mean()

print("Average revenue amount per order:", average_revenue_per_order)

Average revenue amount per order: 21.39423118865867

### Step 17. How many different items are sold?

In [ ]:
num_different_items = chipo['item_name'].nunique()

print("Number of different items sold:", num_different_items)

Number of different items sold: 50